### ISSUE TITLE
Super key blocks window movement

### ISSUE THREAD

**Issue by Wavum** [LinxGem33/Arc-Menu#182] opened 2017-10-09 20:23 UTC
I'm using ``super+shift+arrow-key`` to move a window to my second monitor. The first time I press super, the menu opens up and the focus is on the menu, so I'm no more able to move my window. Wouldn't it be better if the menu appears when i release the super key?

**Comment by lexruee** [comment] 2017-10-09 20:25
Duplicate of https://github.com/LinxGem33/Arc-Menu/issues/76.

**Closed by lexruee** 2017-10-09 20:25 UTC
Labels: duplicate
