### ISSUE TITLE
Improvement suggestion.

### ISSUE THREAD

**Issue by 80avin** [LinxGem33/Arc-Menu#169] opened 2017-10-03 18:24 UTC
I've set **System** key(**Windows** key) to open Arc menu. But, it does a wrong thing by popping up when I push down the **System** key.
Instead, Menu should pop-up when I release the **System** Key !
Additionally, it should not pop-up on **System** key release if I am performing some shortcut combination (**System+1, System+2**, ).

Currently, I can't perform **System+1** shortcut because just as I push down **System** key, Arc menu pops-up and reads **1** as Search query.

**Comment by lexruee** [comment] 2017-10-03 18:40
Duplicate of https://github.com/LinxGem33/Arc-Menu/issues/76.

**Closed by lexruee** 2017-10-03 18:40 UTC
