### ISSUE TITLE
[rfe] launch menu on key release isntead of key press

### ISSUE THREAD

**Issue by zakkak** [LinxGem33/Arc-Menu#76] opened 2017-07-11 18:11 UTC
I (and probably not just me) have a few shortcuts of the form `<Super Key> + <Key>`.

When using the default Gnome launcher using such shortcuts does not trigger the launcher.
However, if I set `<Left Super Key>` as the Arc-menu hotkey, it launches the menu at the press of the button interfering with the rest of the shortcuts, e.g. `<Left Super Key> + e` results in the menu being opened and the letter 'e' being typed in the search box, instead of the action I have mapped it to.

I am not sure but a possible solution could be to trigger the action at the release of the button instead of the press.

**Comment by LinxGem33** [comment] 2017-07-11 18:34
@zakkak 

appreciate the feed back one of the team is currently working on this feature so he will probably reply to you regarding this issue if not i will pass on the message, as i think you make a fair point in your assessment of the current function and trigger of this feature :+1:  however as your probably currently aware Gnome developers never really intended that the `<Super Key>` be used for anything other than to be used as its default function which is to open the overview mode within the shell.

**Comment by lestcape** [comment] 2017-07-11 20:32
@zakkak Who control the short-cut really is gnome shell... He trigger an event when a short-cut is hit. But thats only happens for key-press. There are not way for key-release (This is the gnome way :( ). But well you can try t implement your on mechanism for short-cut, witch of-course will overcomplicate all.

**Comment by lestcape** [comment] 2017-07-11 20:46
@LinxGem33 the answer to arc menu probably is capture 'modifiers-accelerator-activated' https://github.com/GNOME/gnome-shell/blob/695bfb96160033be55cfb5ac41c121998f98c328/js/ui/status/keyboard.js#L354

**Comment by lestcape** [comment] 2017-07-11 20:51
And @LinxGem33, @zakkak is right and this is not related with what gnome shell developers want with the <Super Key>. The problem is not the <Super Key>. The problem is a key-combination that included the <Super Key>. If user set the <Super Key> key for arc menu then they can not used a key combination that include a <Super Key> key for any other things and this is the problem related only with arc-menu.

**Comment by fsteccanella** [comment] 2017-08-14 08:12
I have solved with this tool: https://github.com/hanschen/ksuperkey

**Comment by thebodzio** [comment] 2017-11-03 00:08
I didn't want to start another issue since this is somewhat related thought: menu hotkey settings could be simplified. If the hotkey would be defined as “<Super>” alone it would mean that Arc Menu is used as a “replacement” for “Activities Overview” and thus should be open on key release. Any other key combination should activate menu on key press.

Just my 2¢

**Comment by lestcape** [comment] 2017-11-03 00:59
@thebodzio. Really i think, where this issue can be resolved in bugzilla. Gnome have a chaos with his keybindings and are really difficult to be:

- set
- override
- user with modifier
- capture the release for a shorcut.

Just all are work-arounds on the chaos. See my answer here (some minutes ago): https://askubuntu.com/questions/971177/ubuntu-17-10-gnome-3-firefox-alt-shortcuts-stopped-working

**Comment by thebodzio** [comment] 2017-11-03 01:17
@lestcape Agreed. My comment was intended as a kind of a sidenote to the overall issue here, but I understand you point.

Did you perchance reported this issue in Gnome bugzilla? I'm asking because you seem to be the most familiar with the problem here, hence the best suited to explain it. I'd love to see it resolved, but at the same time I don't think Gnome will do it by itself ;}

**Comment by lestcape** [comment] 2017-11-03 01:30
@thebodzio Really I tried, but probably I could not explain it ok becausewhen I reported it I was learning gnome (as a user and as a developer). In my case, i can try to speak about this using a different canal than bugzilla, because my attempt in bugzilla was a failure. Do you know where i can (email-list, something...)?
See: https://bugzilla.gnome.org/show_bug.cgi?id=778809

**Comment by lestcape** [comment] 2017-11-03 01:44
I have an idea. If his really have the time, to take a look and help us. Ping @fmuellner.

**Comment by thebodzio** [comment] 2017-11-03 02:17
@lestcape Thank you for your response and the link.

Perhaps my observation will seem silly, but I think we should try to explain the whole thing in “smaller words“ ;}. I mean, after all, all that we're after here is to handle the key release event instead of key press. I'm thinking along the lines of reporting something like “Userspace extension cannot handle key release event” and using the very issue here as an example.

Does this make sense?

I mean, at least there's a chance that we'll get some ready solution, since Gnome documentation is not the prettiest in town, if you catch my drift ;}

**Comment by lestcape** [comment] 2017-11-03 02:30
@thebodzio I understand your point, this is probably the worse things, but my point it's not just that.

If you want the answer to this point only, i can give you the answer. Is not implemented, because gnome developers not want/need that. Please see:
https://github.com/GNOME/mutter/blob/e4e200a1dc6ee6e459e5c68916669a48eda33d20/src/ui.c#L617 They are preventing the release key-binding (GDK_RELEASE_MASK) to be active.

Not nice really, but it is what it's...

**Comment by thebodzio** [comment] 2017-11-03 03:03
@lestcape That's a bummer :{

From what I read on Gnome's bugzilla I understood that you're after something more general (forgive me, but my time is quite limited right now, so I didn't read it very diligently). My goal is the same as the OP's and I agree with him that something as simple as handling the key release event would be a way to achieve it.

**Comment by lestcape** [comment] 2017-11-03 03:23
@thebodzio yes, why i try to do is let user to define whatever they want as a keybinding:

- A modifier only.
- A combination between modifiers and normals keys.

If user say he want "something" as a key binding, whatever other existing key binding need to be UNSET. The users are who commandant the desktop, the desktop can not decide for the user. Thats my principal point. So, the keybindings in gnome are thinking to be impositives to the user, not permissives. In my opinion this is the most big issue.

Is a philosophical problem. So, is not just remove or add a code and then is difficult to express, at less for me.

**Comment by thebodzio** [comment] 2017-11-03 03:51
@lestcape Being somewhat a control freak I sympathize with your view.

**Comment by fmuellner** [comment] 2017-11-03 12:21
If I understand you correctly, then you want to use Super_L or Super_R as normal keybindings, but *also* keep it working as &lt;super&gt; modifier in other keybindings. That's simply not possible, treating a key as both a regular key and a modifier needs special handling - there's a reason why the overview key is *not* a normal keybinding that is registered as other shortcuts.

And no, this has *nothing* to do with philosophical questions about control or whatever.

If you want to take over the overview key, then we can allow extensions to disconnect the [overlay-key signal](https://git.gnome.org//browse/gnome-shell/tree/js/ui/main.js#n183) and connect their own handler.

**Comment by lestcape** [comment] 2017-11-03 16:19
@fmuellner "And no, this has nothing to do with philosophical questions about control or whatever".

Gnome not provide a way to disconnected a generic keybinding. As the keybinding can be set for a particular **unknown** (to the extension) GSettingSchema, we can not allow our extensions to disconnect the specific signal with we have conflict and connect it to our own handler (like you suggest for a particular case  the overlay-key signal). There are not a generic way to do the same for others signals if they are know on fly (at the execution time).

Gnome don't provide a way to override all keybindings then. That's mean the keybindings are unmountable in Gnome. Also if they have conflicting, _the extension can not resolve (know how) the conflic_t.

Finally, this mean the extension can not follow the user commandant, ending in a philosophical problem of who have the control over the keybinding (the user or the desktop???). The answer is clear to me. Is the desktop who have the control in gnome, not the users.

**_In mi opinion, this is a wrong conception._**

For another hands, we also can not capture a keybinding on the keyboard release, and this is pretty useful for the desktop actions. An extension is part of the desktop and there are not way to modify or hack the c code in gjs, so we can not changed this fact an we need to priority know the existing keybinding, with is impossible, because also other extensions could decide to use the same keybinding that us decide to use. How we can know that?

**Comment by lestcape** [comment] 2017-11-03 18:15
@thebodzio "Being somewhat a control freak I sympathize with your view.". All us here sympathize with this view, because is the natural view for skilled people. Gnome try the **USER** as an idiot entity without the know field to control the desktop. Linux users are not idiots and the gnome design of keybinding is for idiots.

![linuxrules](https://user-images.githubusercontent.com/1389572/32389527-840a6810-c090-11e7-9d51-36d01e824ceb.jpg)

**Comment by lestcape** [comment] 2017-11-03 18:53
Finally for this issue in question, the only **save way** right now it's set the keybinding statically and not let user to modify the keybinding on run time.  Then try to not conflict with other available extensions. That last part is impossible of course, because you can not control the decision of other developers, so you need to pray to the gods to not one else select your same keybinding. Also not try to use a modifier in gnome as a keybinding, because they don't want this happens and you have not a way to capture the release.

Damn, beautiful workaround, if this is not a conception problem, i don't know how to call it. A creepy gnome implementation?

Thanks @fmuellner

**Comment by lexruee** [comment] 2017-11-03 19:57
@fmuellner 
Thanks for your feedback and technical clarification regarding normal keybindings and modifier keys.

@lestcape and others
Since this seems to be more a technical and gnome-shell related discussion, I would suggest to move this discussion on the gnome-shell mailing list.

**Comment by lestcape** [comment] 2017-11-03 23:17
@lexruee and others, i suggest you to close this issue, like apparently is resolved with this technical clarification.

Have a good day.

**Comment by thebodzio** [comment] 2017-11-04 04:12
Wow! That escalated quickly ;}

**Comment by lestcape** [comment] 2017-11-04 18:17
@thebodzio this is not a war as apparently you think is. I considered the user the most important part of any software. So, it deserved an answer always. At less it deserved know who is responsive for the issue that his have.

What i talking about isn't my personal idea and is complete feasible. Was one of the first commit to muffin after the linuxmint fork of mutter:
https://github.com/linuxmint/muffin/commit/514b181eedf40584cff451e31ff35487dd063bdc

So, if user want to control his keybinding in an extension, the right place to request this is in bugzilla. 

Then this issue is resolved as **NOT POSSIBLE because is not supported in the gnome platform**.

**Comment by thebodzio** [comment] 2017-11-04 18:48
@lestcape Oh no, not at all! I don't think it's any war of any kind. I was referring to the amount of interest this very issue gained after my initial comment :}. Notice the playful “wink” ;}

As to your proposition: more control? Yes, please, I'm all for it.

**Comment by LinxGem33** [comment] 2018-03-17 18:31
> That's simply not possible, treating a key as both a regular key and a modifier needs special handling - there's a reason why the overview key is not a normal keybinding that is registered as other shortcuts.

i agree with the above statement i have been unable to find a workaround for this issue so i think i will now go ahead and mark this issue as closed if anyone find a clean code solution to this enhancement please send a pull request for review.

kind regards

**Closed by LinxGem33** 2018-03-17 18:31 UTC
Labels: wontfix

**Comment by chromevanadium** [comment] 2018-03-27 13:46
OK that the issue may not be solvable, but please do not reset the org.gnome.mutter overlay-key each time on startup, even if "Set menu hotkey" is set to "undefined.
