### ISSUE TITLE
Binding arc menu to [Left Super Key] blocks shortcuts requiring super key

### ISSUE THREAD

**Issue by UltraX3** [LinxGem33/Arc-Menu#138] opened 2017-08-26 18:05 UTC
If I have a shortcut that requires Super key + C for example, this setting will prevent me from being able to do this shortcut.

**Comment by lexruee** [comment] 2017-08-26 18:10
Duplicate of issue https://github.com/LinxGem33/Arc-Menu/issues/76 and https://github.com/LinxGem33/Arc-Menu/issues/107.

**Closed by lexruee** 2017-08-26 18:10 UTC
