### ISSUE TITLE
Arc will crash Gnome if an update occured on Fedora 27

### ISSUE THREAD

**Issue by MylesJohnson** [LinxGem33/Arc-Menu#204] opened 2017-12-04 16:17 UTC
If a package is updated, the next time I login after standby Gnome will crash and restart. I'm not sure what information you need from me to diagnosis this, but let me know and I will provide it.

**Comment by LinxGem33** [comment] 2017-12-04 16:43
please refer to [Reporting-Bug's](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) on the Arc menu wiki guide.

kind regards

**Comment by MylesJohnson** [comment] 2017-12-04 17:11
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 27 (Twenty Seven)
Release:	27
Codename:	TwentySeven
```
```
$ gnome-shell --version
GNOME Shell 3.26.2
```

These are the logs directly following the `dnf update`:
```
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (865862) is greater than comparison timestamp (865851).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 865862.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866013) is greater than comparison timestamp (866003).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866013.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866193) is greater than comparison timestamp (866187).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866193.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866314) is greater than comparison timestamp (866309).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866314.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866345) is greater than comparison timestamp (866340).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866345.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866375) is greater than comparison timestamp (866371).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866375.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866405) is greater than comparison timestamp (866402).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866405.  Working around...
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866465) is greater than comparison timestamp (866464).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:35 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866465.  Working around...
Dec 04 10:33:36 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: last_user_time (866495) is greater than comparison timestamp (866494).  This most likely represents a buggy client sending inaccurat
Dec 04 10:33:36 fedoraxps org.gnome.Shell.desktop[1779]: Window manager warning: 0x1e00011 (Inbox - my) appears to be one of the offending windows with a timestamp of 866495.  Working around...
```

These are the logs on standby:
```
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Failed to apply DRM plane transform 0: Permission denied
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: drmModeSetCursor2 failed with (Permission denied), drawing cursor with OpenGL from now on
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Failed to read EDID from 'eDP-1': No such file or directory
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Screen lock is locked down, not locking
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Failed to read EDID from 'eDP-1': No such file or directory
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Failed to read EDID from 'eDP-1': No such file or directory
Dec 04 11:12:20 fedoraxps org.gnome.Shell.desktop[1120]: Window manager warning: Failed to set power save mode for output eDP-1: Permission denied
Dec 04 11:12:20 fedoraxps gnome-shell[1120]: Failed to read EDID from 'eDP-1': No such file or directory
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: gsignal.c:2641: instance '0x556b2a4efdf0' has no handler with id '9771'
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:20 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:21 fedoraxps audit[1779]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=1779 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Dec 04 11:12:21 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:21 fedoraxps gnome-shell[1779]: clutter_layout_manager_get_child_meta: assertion 'CLUTTER_IS_LAYOUT_MANAGER (manager)' failed
Dec 04 11:12:21 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
Dec 04 11:12:21 fedoraxps gnome-shell[1779]: g_object_set: assertion 'G_IS_OBJECT (object)' failed
```

These are the logs on resume/login:
```
libinput error: libinput bug: timer event6 keyboard: offset negative (-400503)
Removing a network device that was not added
glamor: EGL version 1.4 (DRI2):
JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Some code accessed the property 'SignalManager' on the module 'convenience'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SoundDeviceChooserBase' on the module 'base'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SETTINGS_SCHEMA' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [/home/myles/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js 193]: reference to undefined property Symbol.toPrimitive
Some code accessed the property 'SHOW_INPUT_SLIDER' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
WARNING: addSignalMethods is replacing existing [0x5622e636b900 Gjs_ShowAppsIcon.dash-item-container] connect method
WARNING: addSignalMethods is replacing existing [0x5622e636b900 Gjs_ShowAppsIcon.dash-item-container] disconnect method
WARNING: addSignalMethods is replacing existing [0x5622e636b900 Gjs_ShowAppsIcon.dash-item-container] emit method
Some code accessed the property 'SHELL_KEYBINDINGS_SCHEMA' on the module 'windowManager'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [/home/myles/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/extension.js 45]: reference to undefined property "text"
loading user theme: /home/myles/.themes/VimixDark-Doder/gnome-shell/gnome-shell.css
Extension alternate-tab@gnome-shell-extensions.gcampax.github.com already installed in /home/myles/.local/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/myles/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /home/myles/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/myles/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
Some code accessed the property 'HIDE_ON_SINGLE_DEVICE' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SHOW_PROFILES' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'ICON_THEME' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'HIDE_MENU_ICONS' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'PORT_SETTINGS' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'SHOW_OUTPUT_DEVICES' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Max Id:11
Some code accessed the property 'ICON_THEME_COLORED' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Some code accessed the property 'ICON_THEME_MONOCHROME' on the module 'prefs'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
STACK_OP_ADD: window 0x1e00001 already in stack
STACK_OP_ADD: window 0x1e00001 already in stack
JS WARNING: [/home/myles/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js 750]: reference to undefined property 0
GNOME Shell started at Mon Dec 04 2017 11:14:40 GMT-0500 (EST)
JS WARNING: [/home/myles/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 1001]: reference to undefined property 0
```

**Comment by lexruee** [comment] 2017-12-04 17:41
@MylesJohnson 
Can reproduce the bug using the master branch version? Maybe you are affected by the bug #193 which was fixed in this commit: https://github.com/LinxGem33/Arc-Menu/commit/55a322600072b7ec3523605aa22f59e0e486486f

Cheers

**Comment by LinxGem33** [comment] 2017-12-05 22:05
hi did you manage to reproduce this bug using the master branch as @lexruee suggested?

**Comment by MylesJohnson** [comment] 2017-12-06 03:27
I'm in progress, I'll let you know once one of my packages needs an update. Strangely, it never happened when I simply installed one.

**Comment by MylesJohnson** [comment] 2017-12-08 18:42
It seems better. I did get one random crash, but it wasn't related to updates like the others had been.

**Comment by LinxGem33** [comment] 2017-12-10 04:08
thank you for the reply and letting me know , as i cant reproduce this i shall go ahead and close this issue however if this issue should happen again please don’t hesitate to reopen this issue with the relevant logs etc.

**Closed by LinxGem33** 2017-12-10 04:08 UTC
Labels: low priority
