### ISSUE TITLE
Hold <Super> key.

### ISSUE THREAD

**Issue by AlexGluck** [LinxGem33/Arc-Menu#107] opened 2017-08-01 00:05 UTC
OS fedora 26 at xorg 
When enable hotkey `<Super>`, all system hotkeys combination with <Super> is holded. 
Such as move window to left and expanded `<Super>+Left`

**Comment by AlexGluck** [comment] 2017-08-01 00:07
Expected: open menu and auto close if no input activity.

**Comment by AlexGluck** [comment] 2017-08-01 00:08
Or not steal focus.

**Comment by lexruee** [comment] 2017-08-01 00:15
Duplicate of issue https://github.com/LinxGem33/Arc-Menu/issues/76.

**Closed** 2017-08-01 10:21 UTC
