### ISSUE TITLE
Keybinding doesn't work after lockscreen

### ISSUE THREAD

**Issue by archqob** [LinxGem33/Arc-Menu#95] opened 2017-07-20 05:48 UTC
after lock screen keybinding doesn't, i have to restart gnome-shell session by ALT+F2 'r' to make it work again.

**Comment by lestcape** [comment] 2017-07-20 06:00
The Gnome Display Manager (gdm) is also implemented in gjs and this then change the session mode. When the gdm is enable, is supposed that shell binding will be inhibit. In the way that this is implemented in gnome shell the key-binding connection are destroy, so when gnome shell session starup again you will need to re-enable the keybinding...
```
 this._updateId = Main.sessionMode.connect('updated', Lang.bind(this, this._sessionUpdated)); 
```
```
 _sessionUpdated: function() {
        let sensitive = !Main.sessionMode.isLocked && !Main.sessionMode.isGreeter;
        if(sensitive) {
            // Reconnect here the key-binding handler.
        }
},
```

**Comment by LinxGem33** [comment] 2017-07-20 11:53
@amrsaraya 

appreciate the feed back, we will look into this issue and keep you updated regarding this issue.

kind regards

**Comment by LinxGem33** [comment] 2017-07-20 11:58
@lestcape 

sent you a message in #32

**Comment by lexruee** [comment] 2017-07-26 03:35
@amrsaraya
1) Can you provide more information about your system? (Distribution, GNOME Shell version)

2) Moreover, can you provide us information of your keybinding settings. For example, run the command below to get a dump of your Arc-Menu settings:
```
dconf dump /org/gnome/shell/extensions/arc-menu/
```
3) Lastly, can you list clearly the steps to reproduce your issue?

**Comment by amrsaraya** [comment] 2017-07-27 11:40
@lexruee I'm using Fedora 26 with GNOME-Shell 3.24.3 
can't provide the requested information right now because I'm not home. but i will when i back.

**Comment by lexruee** [comment] 2017-08-01 19:20
@archqob 
Unfortunately, I could not reproduce your issue. Can you git clone the development branch and report back if you still face the same issue?

**Comment by LinxGem33** [comment] 2017-08-02 12:23
@archqob 
please re-test with the latest updates from the main branch.

kind regards

**Comment by archqob** [comment] 2017-08-02 13:43
@LinxGem33  @lexruee 
i tested the new release (v14) and still the same problem.

**Comment by lexruee** [comment] 2017-08-02 13:46
My gut feeling says this is maybe a wayland problem.

**Comment by archqob** [comment] 2017-08-02 13:53
i'm using xorg not wayland.

**Comment by daniel-wtd** [comment] 2017-08-26 20:12
I can report the same with F26 wayland and xorg.

I can see some errors after lock/unlock:

`
Aug 26 22:08:41 nb01 gnome-shell[1678]: JS ERROR: TypeError: this._menuButton is null
                                        MenuSettingsController<._setMenuKeybinding/<@/home/daniel/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/controller.js:105:21
Aug 26 22:08:41 nb01 gnome-shell[1678]: JS ERROR: TypeError: this._menuButton is null
                                        MenuSettingsController<._setMenuKeybinding/<@/home/daniel/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/controller.js:105:21
Aug 26 22:08:41 nb01 gnome-shell[1678]: JS ERROR: TypeError: this._menuButton is null
                                        MenuSettingsController<._setMenuKeybinding/<@/home/daniel/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/controller.js:105:21
Aug 26 22:08:41 nb01 gnome-shell[1678]: JS ERROR: TypeError: this._menuButton is null
                                        MenuSettingsController<._setMenuKeybinding/<@/home/daniel/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/controller.js:105:21`

**Comment by lexruee** [comment] 2017-08-27 00:04
@daniel-wtd 
Thanks for the log. I was able to reproduce the error on a Fedora 26 VM.
Log: http://paste.debian.net/983183

**Closed** 2017-09-02 15:03 UTC
Labels: bug, low priority
