### ISSUE TITLE
icon size cannot hold on under highdpi

### ISSUE THREAD

**Issue by ljhui** [LinxGem33/Arc-Menu#143] opened 2017-09-01 12:33 UTC
I set only show icon with arc menu icon,when I login ,the icon size is shwon normally as blow:
![arc1](https://user-images.githubusercontent.com/16174049/29969523-1a9b1496-8ee6-11e7-9759-289792d49a10.png)
but sometime unlock my computer and relogin,the icon becomes more big,and seems ugly inharmonious with system as blow:
![arc2](https://user-images.githubusercontent.com/16174049/29969612-8057bbfe-8ee6-11e7-884b-76d75b91a88e.png)
```
>lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 26 (Twenty Six)
Release:	26
Codename:	TwentySix
>gnome-shell --version
GNOME Shell 3.24.3
>journalctl /usr/bin/gnome-shell -f -o cat
JS WARNING: [/home/ljhui/.local/share/gnome-shell/extensions/remove-dropdown-arrows@mpdeimos.com/extension.js 45]: reference to undefined property widget.text
JS WARNING: [/home/ljhui/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com/convenience.js 19]: reference to undefined property extension.metadata['gettext-domain']
Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/ljhui/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
JS WARNING: [resource:///org/gnome/shell/ui/status/keyboard.js 708]: reference to undefined property window._inputSources
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
JS WARNING: [/home/ljhui/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js 73]: reference to undefined property blacklist[(i + 1)]
GNOME Shell started at Fri Sep 01 2017 20:35:15 GMT+0800 (CST)
Allocating size to ShellEmbeddedWindow 0x5712aa6c20 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
JS WARNING: [/home/ljhui/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js 109]: reference to undefined property this._panelHeight
Allocating size to ShellEmbeddedWindow 0x5712aa6c20 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

```
I'm not certain it is concern with highdpi issue, my resolution is 2560x1440

**Comment by lexruee** [comment] 2017-09-01 14:13
I think this issue maybe related to this one: https://github.com/LinxGem33/Arc-Menu/issues/117

@jbuisine Do you also encounter this issue reported by @ljhui?

**Comment by ljhui** [comment] 2017-09-01 15:09
I think it's a same issue just as jbuisine report.  I install the arc menu and set a  good looked icon size, but when I restart to login or close then login, the icon size become smaller, so I adjust the icon size  bigger so that it can shown well when I restart my PC,  but if I logout and then login, it 
 backs to a bigger icon. while I think the small icon is " the normal size", jbuisine says the big icon is " the normal size", so we are facing same issue actually.

**Comment by LinxGem33** [comment] 2017-09-02 15:06
duplicate of issue #117

**Closed by LinxGem33** 2017-09-02 15:06 UTC
Labels: low priority
