### ISSUE TITLE
System Icon Remains Behind Custom Menu Icon

### ISSUE THREAD

**Issue by SegFault0x0** [LinxGem33/Arc-Menu#174] opened 2017-10-04 20:47 UTC
When using the [Adapta](https://github.com/adapta-project/adapta-gtk-theme) theme, the 9-dot "Applications" icon remains behind my custom Arch icon as in the picture.

![arc icon](https://user-images.githubusercontent.com/10413170/31198163-4e8feba0-a921-11e7-90aa-bf0d8e5db2fc.png)

Both the "Arc Menu" and "System" icon selections have been replaced by the 9-dot icon.  This is how it looks when I select either one as the menu icon:

![arc app icon](https://user-images.githubusercontent.com/10413170/31198491-783841b8-a922-11e7-8c11-f2cdca9189c8.png)

This doesn't occur if I use any of the Arc themes.  I'm using gnome-shell 3.24.3 on Arch 4.9.40-1-lts.

**Comment by lexruee** [comment] 2017-10-04 20:53
This is a duplicate of #124. In short, this fixed by latest Adapta version (see  https://github.com/adapta-project/adapta-gtk-theme/issues/482).

**Closed by lexruee** 2017-10-04 20:53 UTC
Labels: duplicate, wontfix

**Comment by SegFault0x0** [comment] 2017-10-05 00:36
Got it, thanks!
