### ISSUE TITLE
System, keyboard, and mouse locking up

### ISSUE THREAD

**Issue by AccountOneOff** [LinxGem33/Arc-Menu#148] opened 2017-09-12 02:42 UTC
I've ran into this bug three or four different times and each time I couldn't get out of it. I have Dash to Panel installed and that's the only thing the mouse could interact with (right-clicking menus and icons). Otherwise opening a terminal/tty doesn't work and interacting with the desktop doesn't either. 

Each time this has happened I've had to restart my PC with Alt+SysRq REISUB. I think it has something to do with pressing the Super key while alt-tabbing as that's what I did when it locked up just recently but I can't seem to reproduce it.

This is what it looks like when it happens:
![arc menu](https://i.imgur.com/Or745AD.png)

Clicking/right-clicking the Arc menu doesn't do anything either.

***

Ubuntu 17.04

Gnome Shell 3.24.2

    journalctl /usr/bin/gnome-shell -f -o cat

    st_widget_get_theme_node called on the widget [0x55b5efa1dfb0 StBin (" ")] which is not in the stage.
    st_widget_get_theme_node called on the widget [0x55b5efa2eaa0 ShellGenericContainer.panel-button:last-child first-child (" ")] which is not in the stage.
    st_widget_get_theme_node called on the widget [0x55b5efa1a720 StBoxLayout.panel-status-menu-box:last-child first-child (" ")] which is not in the stage.
    GNOME Shell started at Mon Sep 11 2017 19:20:34 GMT-0700 (PDT)
    [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.59/org/ayatana/NotificationItem/_modules_kdeconnect_devices_7c37d5d233e15690
    JS WARNING: [resource:///org/gnome/shell/ui/dash.js 760]: reference to undefined property oldApps[oldIndex]
    JS WARNING: [resource:///org/gnome/shell/ui/appDisplay.js 1298]: reference to undefined property this.name
    JS WARNING: [/home/cxf/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js 963]: reference to undefined property oldWin[oldIndex]
    [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.92/org/ayatana/NotificationItem/software_update_available
    _cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed

**Comment by LinxGem33** [comment] 2017-09-12 13:46
@AccountOneOff 

thank you for logging your issue with us i shall allocate a priority and if we need further information regarding your issue we will contact you accordingly.

kind regards

**Comment by LinxGem33** [comment] 2017-12-06 15:32
are you still having this issue on your system?

**Comment by AccountOneOff** [comment] 2017-12-06 23:38
No, I haven't run into it since but like I said I'm not exactly sure how to reproduce it.

**Comment by LinxGem33** [comment] 2017-12-10 04:03
hi Im going to close this issue now as i cant reproduce if you should run into this issue again please dont hesitate to reopen this issue with the relevant logs etc.

**Closed by LinxGem33** 2017-12-10 04:03 UTC
Labels: low priority
