### ISSUE TITLE
error loading extension ubuntu 17.10

### ISSUE THREAD

**Issue by deepakSP** [LinxGem33/Arc-Menu#189] opened 2017-10-19 19:36 UTC
i am getting "error loading extension" message on freshly installed ubuntu 17.10 (default session).

**Comment by LinxGem33** [comment] 2017-10-19 19:44
Please refer to the Wiki for a guide on how to report bugs:
https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

**Edit:**
Overall, this is just a Ubuntu problem as the Ubuntu people decided to ship a broken or incomplete GNOME Desktop environment with Ubuntu 17.10.
In short, this can be fixed by installing the following dependencies, which are usually installed per default on any sane GNOME-based Linux distribution.

```
sudo apt install -y gnome-shell-extensions gnome-tweak-tool gnome-menus 
```
The main problem is that it seems that Ubuntu 17.10 won't ship gnome-shell-extensions per default [1]. Consequently, their GNOME Desktop is just broken by design as it will lack dependencies like gir1.2-gmenu-3.0.

[1] https://wiki.ubuntu.com/DesktopTeam/GNOME/MIR_List

**Comment by deepakSP** [comment] 2017-10-19 20:04
thank you @LinxGem33 though installing gnome-shell-extensions messing up the DE, i guess we have to wait if ubuntu address gnome-session issue.

**Comment by Kerberos7** [comment] 2017-10-20 06:32
The following worked for me.

`sudo apt install -y  gnome-shell-extensions gnome-tweak-tool gnome-menus `

**Comment by deepakSP** [comment] 2017-10-20 06:41
@Kerberos7 yes but  for me it removes ubuntu default session (x11 and wayland), I can see 2 gnome session gnome classic and gnome x11 and both looks ugly

**Comment by lexruee** [comment] 2017-10-20 07:35
@deepakSP If you want to use a GNOME desktop, I would suggest to use Fedora, Debian, or Antergos. This might sound harsh but Ubuntu 17.10 is just a broken GNOME system. 

Overall, it's just a Ubuntu 17.10 problem. The Ubuntu Desktop Team have their own vision how their GNOME desktop should look like. So let them pursue their vision and don't try to fix a broken GNOME system.

**Comment by deepakSP** [comment] 2017-10-20 08:58
@LinxGem33 yes i might switch to opensuse.

though arc-menu is not working for me in gnome-session as well with nvidia drive active.

**Comment by LinxGem33** [comment] 2017-10-20 10:33
@lexruee is right at the moment Ubuntu still has problems integrating the Gnome desktop regarding missing dependencies etc I’m sure these will be fixed in further releases but as of now the dependencies which i listed in my previous message are needed not just for Arc menu but for other extensions also, so for now you can either wait for the issues to be fixed in the Ubuntu releases  or install a alternative Gnome distribution like the ones previously mentioned.

unfortunately as Gnome extension developers there is not much we can do if Ubuntu haven’t shipped all the needed dependencies apart from tell you which are missing and which are needed to be installed it wont just be the Arc menu team to have this issue, but like i said I’m sure further releases of Ubuntu will address these issues.

for now please see below supported distributions for the Gnome desktop environment should you wish to change until the issues are addressed in Ubuntu.

https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions

**Comment by deepakSP** [comment] 2017-10-20 10:48
@LinxGem33 finally i was able to install arc-menu and gnome-session properly. Thank you for your assistance and awesome extension.

**Closed** 2017-10-20 11:04 UTC

**Comment by lexruee** [comment] 2017-10-23 15:01
I post this launchpad link here just for documentation purposes as it is related to Arc-Menu/Ubuntu issue.

__Gnome shell menu extensions won't install on 17.10__:
https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/1711768
