### ISSUE TITLE
I can't paste, copy or modify the hotkey from the search imput..

### ISSUE THREAD

**Issue by Warmuser** [LinxGem33/Arc-Menu#131] opened 2017-08-18 13:51 UTC
Can you please add these settings, soon? Let me know If it possible, thanks!

I'm on Manjaro 17.0.2 with GNOME 3.24.2.

PS: Beautiful extension! :)

UP! Sometimes it doesn't find some installed (from pamac) programs.

**Comment by lexruee** [comment] 2017-08-19 11:33
@Warmuser 
Thanks for the report. Indeed, CNP (Copy/Cut and Paste) does not work on my system either (Debian Sid/ GNOME 3.22). I must admit I never tested that before.

Technically speaking, I'm not sure if the CNP feature of the search text box is missing or just a strange bug.

Anyways, I'll look into this issue as the current state right now is clearly a UX bug.

**Comment by Warmuser** [comment] 2017-08-19 12:14
@lexruee thanks for the answers anyway I don't use the GNOME Software Center since I switched from Ubuntu to Manjaro. I always used Pamac or the online GNOME Extension. I downloaded all my extension from there. :)

Anyway I made a video to show you what is the problem: https://www.youtube.com/watch?v=CDYfMrHIliY :)

**Comment by LinxGem33** [comment] 2017-09-30 22:00
@Warmuser 

appreciate your feed back, this issue has now been fixed by @lexruee in the [refactor-search-box](https://github.com/lexruee/Arc-Menu/commit/91550dce808ef850076b7e35970300958509b5e1) branch.

lexruee has re-written the code base for this feature in short its new code developed for this feature and many more for future development you can test this branch and let us know if the issue is now fixed.

i will now close this issue as i am satisfied that this issue is resolved after testing this new code base.

kind regards

**Closed by LinxGem33** 2017-09-30 22:00 UTC
Labels: bug, enhancement, low priority

**Comment by lexruee** [comment] 2017-09-30 22:28
As a side note: The refactor-search-box is also available on LinxGem33's repo: https://github.com/LinxGem33/Arc-Menu/tree/refactor-search-box

I hope it's okay that I ping @itmitica and @archqob as well. Both have also reported some search box related input bugs (#77 and #150). Any feedback on the new search box implementation is welcomed. 

As LinxGem33 mentioned, the new search box implementation will hopefully be merged after some minor refinements :smile: .

**Comment by Warmuser** [comment] 2017-10-01 08:06
@LinxGem33 Wow, surely I will test the new version and give you the response. Thanks! :)
