### ISSUE TITLE
The size of arc-menu is increasing and the search-box too

### ISSUE THREAD

**Issue by archqob** [LinxGem33/Arc-Menu#153] opened 2017-09-16 05:57 UTC
**Issue:** when search for a long application's name like "GNU Image Manipulation Program" 

- **Expected behavior:** search-box size remain constant and it hides the older written characters Sequentially.
- **Real behavior:** the size of arc-menu is increasing and the search-box too.

**Screenshot:**
![screenshot from 2017-09-16 07-53-13](https://user-images.githubusercontent.com/21042432/30509584-d92f5ba6-9abc-11e7-86c3-ef84d22baea9.png)

**Comment by lexruee** [comment] 2017-09-16 06:46
Thanks for the report. Fix a bug (#150)  and you will get two more bugs :-). In my opinion this appears to be a minor issue and also more a UX related bug. 

One could argue it's feature that the menu resizes itself depending on the user input.
Overall, it's UX question how the menu should behave. 

@LinxGem33 What are you thoughts about this?

**PS:** Calling every new issue a UX bug becomes more and more my standard catchphrase :rofl:. Anyways, [get schwifty](https://www.youtube.com/watch?v=I1188GO4p1E) :smile:!

**Comment by LinxGem33** [comment] 2017-09-16 12:26
@lexruee 

i agree it could be classed as a UX feature but the normal behaviour is to have the box set without extending  maybe set a character char to a set amount to fix its position, but yeah i think we should just fix the box size would probably be the best route :+1: 

PS.. ive now added a UX bug label

**Comment by lexruee** [comment] 2017-09-17 09:57
@LinxGem33 

I played around a little bit with the `stylesheet.css`  and found a simple hack to fix this issue.
Basically, we just need to set the max-width property for `St.Entry` widget to an arbitrary number, like zero pixels. I tested this on Arch/GNOME Shell 3.24 and it seems to work. Here's the example code for the `stylesheet.css` :
```css
#search-entry {
    max-width: 0px;
}
```

Although this hack works, I don't really like this solution as I don't have a well understanding how GNOME Shell CSS theming works. I hope someone else has a better idea how we can fix the resize issue of the menu.

Another approach would be to set a width value (e.g., `40em`) in `stylesheet.css`  for the menu as shown below:
```css
.main-box {
    height: 38em;
    width: 40em;
}
```

**Comment by LinxGem33** [comment] 2017-09-17 11:09
@lexruee 

its a good idea but regarding setting the .main-box { what will happen is if there is different elements on the menu which extend the width the menu box wont extend automatically and your left with overlapping elements please see #6 , but regarding the search-entry { this would be the better option if you wanted to employ a css styling rule as it would only affect this element , hope that helps a little :confused:

**Comment by lexruee** [comment] 2017-09-17 13:18
@LinxGem33 
> regarding setting the .main-box  what will happen is if there is different elements on the menu which extend the width the menu box wont extend automatically and your left with overlapping elements

I see. Setting a width value for `.main-box`  introduces new theming issues.

The problem with the `search-entry` hack is that I find out this solution by try and error, and I don't know why it works :smile:. I could not find any useful information about the `max-width` property on the usual online resources:

* https://www.roojs.org/seed/gir-1.2-gtk-3.0/seed/St.Entry.html
* https://developer.gnome.org/st/stable/StEntry.html
* https://developer.gnome.org/st/stable/

However, what I found out is the following:
* [StEntry](https://developer.gnome.org/st/stable/StEntry.html) is derived from [StWidget](https://developer.gnome.org/st/stable/StWidget.html), which in turn is derived from [ClutterActor](https://developer.gnome.org/clutter/stable/ClutterActor.html).
* Moreover, there is a class called [StThemeNode](https://developer.gnome.org/st/stable/st-st-theme-node.html) which represents the CSS style information of themed objects like [ClutterActor](https://developer.gnome.org/clutter/stable/ClutterActor.html) and its derived classes.
* Now, the interesting fact is that this StThemeNode object supports the `max-width` theming property (see [here](https://github.com/GNOME/gnome-shell/blob/6fc5b0477ba1c77b6bcdd23e07254fbe97c92b83/src/st/st-theme-node.c#L1822)). So I guess this [max-width](https://developer.mozilla.org/en-US/docs/Web/CSS/max-width) property does what it supposed to do. It sets the maximum width of an element.

Anyways, GNOME Shell CSS theming is still black magic to me :smile:.

**Comment by LinxGem33** [comment] 2017-09-17 17:30
@lexruee 

also just to add try and play with **em**'s and **px** (as em's scales much better across themes) and if your not happy and you would rather employ a code solution try and set a specific character char although this has the down side of not allowing the user to input more than the specified character length but how many programs really have extended names :smile:

**Comment by lexruee** [comment] 2017-09-17 18:03
@LinxGem33 

Thanks for the links. Hmm, the default font-size in the GNOME Shell Adwaita theme appears to be 11pt [1]. So the font size is approx. 15px or 0.938em [2]. This means 265px ≈ 17.667em. Indeed, the value 17.667em seems to work fine on my machine :smile:.


[1] [gnome-shell.css#L23](https://github.com/GNOME/gnome-shell/blob/master/data/theme/gnome-shell.css#L23)
[2] http://pxtoem.com/

**Comment by lexruee** [comment] 2017-09-17 19:00
@archqob 
Thanks for testing the pull request #156. Regarding your comment:
> I tested the PR. the size of increasing has been limited to like 5x chars 'a' then it stop increasing, but it still increasing "with limited size"

Can you provide the following details: 
* GNOME Shell version
* Linux distribution & version
* Default font size (see gnome tweak tool)
* Used GNOME Shell Theme
* Monitor resolution/HDPI Monitor

**Comment by archqob** [comment] 2017-09-17 20:07
@lexruee There is no need to thank me for anything, i'm happy to help even with this small rule.

- **GNOME Shell:** 3.24.3
- **Distribution:** Fedora 26
- **Default Font:** Roboto '9.75'
- **GNOME Shell Theme:** [Flat-Plat](https://github.com/nana-4/Flat-Plat)
- **Monitor Resolution:** 1366 x 768 (16:9)

**Comment by lexruee** [comment] 2017-09-18 11:29
@LinxGem33 @archqob 
I could reproduce the issue with the same theming settings on a 1366 x 768 screen.

I don't know but maybe we should nevertheless use `max-width: 0em` for the element `#search-entry`:
https://github.com/LinxGem33/Arc-Menu/blob/Development-branch/stylesheet.css#L41

At least this hack fixes the issue for most of the themes, I guess.

**Comment by LinxGem33** [comment] 2017-09-18 12:28
@lexruee 
ive also tested and can confirm your fix works there is no extra however i have re-orderd the css hierarchy please test and let me know if this fixes the issue now it is fixed on my system. 

css fix - https://github.com/LinxGem33/Arc-Menu/blob/Development-branch/stylesheet.css

**Comment by lexruee** [comment] 2017-09-20 11:17
@LinxGem33 
It seems that this is a Flat-Pat specific issue. But `max-width: 0em` fixes the issue on my test machine:

```css
#search-entry {
    max-width: 0em;
}
```

**Comment by LinxGem33** [comment] 2017-09-22 13:51
closing due to appropriate resolution.

**Closed by LinxGem33** 2017-09-22 13:51 UTC
Labels: low priority, UX bug
