### ISSUE TITLE
Arc Menu wont open File Manager

### ISSUE THREAD

**Issue by stevedude** [LinxGem33/Arc-Menu#164] opened 2017-09-29 20:18 UTC
I am running Gnome 3.24 on Manjaro with NVidia GTS 450 graphics card. Arc Menu works wonderfully with the exception of the side panel locations/folders. IE: Home, Documents, Downloads, etc. I will click on one of the locations, the cursor will be busy for a moment, then nothing launches.

Everything else works fine and I can launch FILES or NEMO from the Accessories icon, just not from the side panel.

**Comment by lexruee** [comment] 2017-09-29 20:28
@stevedude 
Can you please provide some logs that capture the occurrence bug? For example:
```
journalctl /usr/bin/gnome-shell -f > loggile.txt
```
For more details see:
https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

**Comment by stevedude** [comment] 2017-10-01 16:41
Multiple lines of what appears to be the same error:
Oct 01 12:34:26 steve-Manjaro gnome-shell[31054]: Failed to load resource:///org/gnome/shell/theme/assets/dot/running1-bottom.svg: The resource at “/org/gnome/shell/theme/assets/dot/running1-bottom.svg” does not exist

**Comment by Trejjam** [comment] 2017-10-14 13:56
I had same problem, it is caused by https://extensions.gnome.org/extension/307/dash-to-dock/ plugin

**Comment by stevedude** [comment] 2017-10-18 14:28
Thanks @Trejjam , I'll disable Dash-To-Dock and report back.

**Comment by stevedude** [comment] 2017-11-17 04:20
Figured it out. I used to run Manjaro Deepin and my .config/mimeapp.list had the Deepin File Manager as the default file manager. Once I changed that entry to nemo.desktop, all is working well.

**Comment by LinxGem33** [comment] 2017-12-06 15:29
glad you found the solution i will close this issue now.

**Closed by LinxGem33** 2017-12-06 15:29 UTC
Labels: low priority
